CREATE TABLE users (
user_id INTEGER NOT NULL AUTHO_INCREMENT,
user_name VARCHAR(50) NOT NULL,
first_name VARCHAR(50) NOT NULL,
last_name VARCHAR(50) NOT NULL,
email VARCHAR(50) NOT NULL,
password VARCHAR(50) NOT NULL,
created_at timestamp WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
PRIMARY KEY (user_id),
);
